server.tomcat.mbeanregistry.enabled: true
management.server.port: 9090
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus
          - metrics
